// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameFlywaySchemaHistory = "flyway_schema_history"

// FlywaySchemaHistory mapped from table <flyway_schema_history>
type FlywaySchemaHistory struct {
	InstalledRank int32     `gorm:"column:installed_rank;type:int;primaryKey" json:"installed_rank"`
	Version       *string   `gorm:"column:version;type:varchar(50)" json:"version"`
	Description   string    `gorm:"column:description;type:varchar(200);not null" json:"description"`
	Type          string    `gorm:"column:type;type:varchar(20);not null" json:"type"`
	Script        string    `gorm:"column:script;type:varchar(1000);not null" json:"script"`
	Checksum      *int32    `gorm:"column:checksum;type:int" json:"checksum"`
	InstalledBy   string    `gorm:"column:installed_by;type:varchar(100);not null" json:"installed_by"`
	InstalledOn   time.Time `gorm:"column:installed_on;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"installed_on"`
	ExecutionTime int32     `gorm:"column:execution_time;type:int;not null" json:"execution_time"`
	Success       bool      `gorm:"column:success;type:tinyint(1);not null;index:flyway_schema_history_s_idx,priority:1" json:"success"`
}

// TableName FlywaySchemaHistory's table name
func (*FlywaySchemaHistory) TableName() string {
	return TableNameFlywaySchemaHistory
}
