// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/go-sonic/sonic/consts"
)

const TableNameMeta = "meta"

// Meta mapped from table <meta>
type Meta struct {
	ID         int32           `gorm:"column:id;type:integer;primaryKey" json:"id"`
	Type       consts.MetaType `gorm:"column:type;type:bigint;not null" json:"type"`
	CreateTime time.Time       `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime *time.Time      `gorm:"column:update_time;type:datetime" json:"update_time"`
	MetaKey    string          `gorm:"column:meta_key;type:varchar(255);not null" json:"meta_key"`
	PostID     int32           `gorm:"column:post_id;type:integer;not null" json:"post_id"`
	MetaValue  string          `gorm:"column:meta_value;type:varchar(1023);not null" json:"meta_value"`
}

// TableName Meta's table name
func (*Meta) TableName() string {
	return TableNameMeta
}
