// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"github.com/go-sonic/sonic/consts"
)

const TableNameOption = "option"

// Option mapped from table <option>
type Option struct {
	ID          int32             `gorm:"column:id;type:integer;primaryKey" json:"id"`
	CreateTime  time.Time         `gorm:"column:create_time;type:datetime;not null" json:"create_time"`
	UpdateTime  *time.Time        `gorm:"column:update_time;type:datetime" json:"update_time"`
	OptionKey   string            `gorm:"column:option_key;type:varchar(100);not null" json:"option_key"`
	Type        consts.OptionType `gorm:"column:type;type:bigint;not null" json:"type"`
	OptionValue string            `gorm:"column:option_value;type:longtext;not null" json:"option_value"`
}

// TableName Option's table name
func (*Option) TableName() string {
	return TableNameOption
}
