// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNamePostCategory = "post_category"

// PostCategory mapped from table <post_category>
type PostCategory struct {
	ID         int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time  `gorm:"column:create_time;type:datetime(6);not null" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime(6)" json:"update_time"`
	CategoryID int32      `gorm:"column:category_id;type:int(11);not null;index:post_category_category_id,priority:1" json:"category_id"`
	PostID     int32      `gorm:"column:post_id;type:int(11);not null;index:post_category_post_id,priority:1" json:"post_id"`
}

// TableName PostCategory's table name
func (*PostCategory) TableName() string {
	return TableNamePostCategory
}
